# Custom variables
docs-ver: v1.0.0-beta.7
src-ver:  v1.0.0-beta.4
repo:     https://github.com/felixdorner/baseline
download: https://github.com/felixdorner/baseline/releases/latest

# Collections
collections:
  instructions:
    output: false
