# Custom variables
docs-ver: v1.0.0-beta
src-ver:  v1.0.0-beta
repo:     https://github.com/felixdorner/starrrtcss
download: https://github.com/felixdorner/starrrtcss/releases/latest

# Collections
collections:
  instructions:
    output: false
