# Custom variables
docs-ver: v1.1.0
src-ver:  v1.1.0
repo:     https://github.com/felixdorner/cascade
download: https://github.com/felixdorner/cascade/releases/latest

# Collections
collections:
  instructions:
    output: false
