# Custom variables
docs-ver: v1.0.0-beta.3
src-ver:  v1.0.0-beta.1
repo:     https://github.com/felixdorner/StarrrtCSS
download: https://github.com/felixdorner/StarrrtCSS/releases/latest

# Collections
collections:
  instructions:
    output: false
