# Custom variables
version:  v0.2.0
repo:     https://github.com/felixdorner/starrrt
download: https://github.com/felixdorner/starrrt/releases/download/v0.1.0/starrrt.min.css

# Collections
collections:
  instructions:
    output: false
