# Custom variables
version:  v0.4.0
repo:     https://github.com/felixdorner/starrrt
download: https://github.com/felixdorner/starrrt/releases/download/v0.4.0/starrrt.min.css

# Collections
collections:
  instructions:
    output: false
